"""add currency to tier model

Revision ID: edecc7539e18
Revises: f772f4b5139a
Create Date: 2025-04-07 22:07:47.542447

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "edecc7539e18"
down_revision = "f772f4b5139a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tier", sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tier", "currency")
    # ### end Alembic commands ###
