name: Continuous Delivery

on:
  push:
    branches: 
      - main
      - develop
      - hotfix/**

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install python-semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Semantic Release (bump & tag)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish

      - name: Get version tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    
      - name: Login to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_PAT }}
        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push image
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          SERVICE: ${{ github.event.repository.name }}
        run: |
          TAG=${VERSION#v}
          docker build -t ghcr.io/fotapol/${SERVICE}:${TAG} \
                       -t ghcr.io/fotapol/${SERVICE}:latest .
          docker push ghcr.io/fotapol/${SERVICE}:${TAG}
          docker push ghcr.io/fotapol/${SERVICE}:latest
